name: Deploy DocFx
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install DocFx
        run: dotnet tool update -g docfx

      - name: Build Project
        run: dotnet build

      - name: Generate Documentation
        run: |
          docfx metadata
          docfx build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: fz3hra/server_blog_post_manager.github.io
          publish_branch: gh-pages
          publish_dir: _site